{% set version = '0.0.13' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-overviewr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/overviewR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/overviewR/overviewR_{{ version }}.tar.gz
  sha256: 09e559e552eae051523ea4c0d0134b2d8e3420ea5d68b854753608929ac4e28d

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-data.table >=1.14.2
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.3.2
    - r-ggrepel >=0.8.2
    - r-ggvenn >=0.1.8
    - r-rlang
    - r-tibble >=3.0.1
    - r-tidyr
  run:
    - r-base
    - r-data.table >=1.14.2
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.3.2
    - r-ggrepel >=0.8.2
    - r-ggvenn >=0.1.8
    - r-rlang
    - r-tibble >=3.0.1
    - r-tidyr

test:
  commands:
    - $R -e "library('overviewR')"           # [not win]
    - "\"%R%\" -e \"library('overviewR')\""  # [win]

about:
  home: https://github.com/cosimameyer/overviewR
  license: GPL-3.0-only
  summary: Makes it easy to display descriptive information on a data set.  Getting an easy overview
    of a data set by displaying and visualizing sample information in different tables
    (e.g., time and scope conditions).  The package also provides publishable 'LaTeX'
    code to present the sample information.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
# Type: Package

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: overviewR
# Title: Easily Extracting Information About Your Data
# Version: 0.0.13
# Authors@R: c( person("Cosima", "Meyer", , "cosima.meyer@gmail.com", role = c("cre", "aut")), person("Dennis", "Hammerschmidt", , "dennis_hammerschmidt@yahoo.com", role = "aut") )
# Description: Makes it easy to display descriptive information on a data set.  Getting an easy overview of a data set by displaying and visualizing sample information in different tables (e.g., time and scope conditions).  The package also provides publishable 'LaTeX' code to present the sample information.
# License: GPL-3
# URL: https://github.com/cosimameyer/overviewR
# BugReports: https://github.com/cosimameyer/overviewR/issues
# Depends: R (>= 3.5.0)
# Imports: data.table (>= 1.14.2), dplyr (>= 1.0.0), ggplot2 (>= 3.3.2), ggrepel (>= 0.8.2), ggvenn (>= 0.1.8), rlang, tibble (>= 3.0.1), tidyr
# Suggests: countrycode, covr, devtools, knitr, magrittr, pkgdown, rmarkdown, spelling, testthat, xtable
# VignetteBuilder: knitr, rmarkdown
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-02-15 07:41:16 UTC; cosima
# Author: Cosima Meyer [cre, aut], Dennis Hammerschmidt [aut]
# Maintainer: Cosima Meyer <cosima.meyer@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-02-15 07:50:02 UTC
